/** Tailwind 设计令牌：颜色映射到 global.css 的 :root 变量，调色只改变量。 */
export default {
  content: ["./src/renderer/index.html", "./src/renderer/src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        paper: "var(--color-paper)",
        ink: "var(--color-ink)",
        line: "var(--color-line)",
        brand: "var(--color-brand)",
        branddeep: "var(--color-branddeep)",
        link: "var(--color-link)",
        ok: "var(--color-ok)",
        okdeep: "var(--color-okdeep)",
        warn: "var(--color-warn)",
        warndeep: "var(--color-warndeep)",
        danger: "var(--color-danger)",
        dangerdeep: "var(--color-dangerdeep)",
        claw: "var(--color-claw)",
        muted: "var(--color-muted)",
        faint: "var(--color-faint)",
        tint: "var(--color-tint)",
        surface: "var(--color-surface)",
        field: "var(--color-field)",
        hot: "var(--color-hot)",
        okbg: "var(--color-okbg)",
        warnbg: "var(--color-warnbg)",
        dangerbg: "var(--color-dangerbg)",
        page: "var(--color-page)",
        card: "var(--color-card)",
        panel: "var(--color-panel)",
        linesoft: "var(--color-linesoft)",
        switch: "var(--color-switch)",
        logo: "var(--color-logo)",
        title: "var(--color-title)",
        body: "var(--color-body)",
        subtle: "var(--color-subtle)",
        placeholder: "var(--color-placeholder)",

      },
      fontFamily: {
        sans: ['"Microsoft YaHei UI"', '"PingFang SC"', '"Segoe UI"', "system-ui", "sans-serif"],
        mono: ["Consolas", "ui-monospace", "monospace"],
      },
    },
  },
  plugins: [],
};
